accountexists() ::= <<

$mailboxTop()$
                    <div class="container-fluid">
                      <div class="row-fluid">
                        $mailboxLeft()$

                        <div class="span9">
                          <div class="hero-unit">

                            <p>Account already exists! you can check your mail now!</p>
                            </div>
                          </div>
                        </div><!--/span-->
                </div><!--/row-->
>>