error() ::= <<

                    <div class="container-fluid">
                      <div class="row-fluid">

                        <div class="span9">
                          <div class="hero-unit">
                            Oops! Something went wrong!
                            </div>
                          </div>
                        </div><!--/span-->
                </div><!--/row-->
>>