home() ::= <<
<body>
<div class="container-fluid">
<div class="row-fluid">
                    <div class="hero-unit">
                    <div align="center">
                        New User? <a href="/register">Register</a>
                        <br/><br/>

                        Already have an account? <a href="/login">Login</a>
                        </div
                    </div>
          </div>
      </div><!--/row-->
</div><!--/.fluid-container-->
</body>
>>