invalidcurrentpassword() ::= <<

$mailboxTop()$
                    <div class="container-fluid">
                      <div class="row-fluid">
                        $mailboxLeft()$

                        <div class="span9">
                          <div class="hero-unit">
                          Invalid current password.<br/>
                          Try again to <a href="/changepassword">change password</a>!

                            </div>
                          </div>
                        </div><!--/span-->
                </div><!--/row-->
>>