mailbox() ::= <<

<table class="table breadcrumb">
                  <tr>
                    <td>  </td>

                    <td><a href="#">Delete</td>
                    <td><a href="#">Mark Junk</td>
                    <td><a href="#">Move</td>
                    <td><a href="#">Search</td>
                    </table>

                    <div class="container-fluid">
                      <div class="row-fluid">
                        <div class="span3">
                          <div class="well sidebar-nav">
                            <ul class="nav nav-list">
                               <li><a href="/compose">Compose</a></li>
                               <hr/>
                              <li><a href="/checkmail">Check Mail</a></li>
                              <hr/>
                              <li><a href="/inbox">Inbox</a></li>
                              <li><a href="/draft">Draft</a></li>
                              <li><a href="/sent">Sent</a></li>
                              <li><a href="/junk">Junk</a></li>
                              <li><a href="/trash">Trash</a></li>
                              <hr/>
                              <li><a href="/account">Account</a></li>
                              <hr/>
                              <li>Smart Folders</li>
                             <br>
                              <li><a href="#">Edit | Refresh</a></li>
                              <hr/>

                              <li><a href="/logout">Logout</a></li>

                            </ul>
                          </div><!--/.well -->
                        </div><!--/span-->


                        <div class="span9">
                          <div class="hero-unit">

                            <div align="center">
                            Please setup your <a href="/account">Account</a> to start!
                            And then Check Mail</a>
                            </div>
                            </div>
                          </div>
                        </div><!--/span-->
                </div><!--/row-->
>>