mailboxTop() ::= <<

<div class="table breadcrumb pull-left">

<div align="center">

<form class="form-inline" style="display:inline;" action="/searchemail" method="GET">
   <input type="search" name="search" id="search" name="search" list="field">
   <datalist id="field">
               <option value="from:">
               <option value="to:">
               <option value="subject:">
               <option value="body:">
           </datalist>
   <input type="submit" class="btn btn-default" value="Search" name="submit" id="submit" >
</form>

</div>
</div>

>>