mailboxLeft() ::= <<
<div class="span3">
                          <div class="well sidebar-nav">
                            <ul class="nav nav-list">
                               <li><a href="/compose"><span class="glyphicon glyphicon-pencil">&nbsp&nbspCompose</a></li>
                               <hr/>
                              <li><a href="/checkmail"><span class="glyphicon glyphicon-refresh"></span>&nbsp&nbspCheck Mail</a></li>
                              <hr/>
                              <li> <a href="/inbox"><span class="glyphicon glyphicon-inbox"></span>&nbsp&nbspInbox</a></li>
                              <li><a href="/spam"><span class="glyphicon glyphicon-warning-sign"></span>&nbsp&nbspSpam</a></li>
                              <li><a href="/sent"><span class="glyphicon glyphicon-send"></span>&nbsp&nbspSent</a></li>
                              <li><a href="/trash"><span class="glyphicon glyphicon-trash"></span>&nbsp&nbspTrash</a></li>
                              <hr/>
                              <li><a href="/addfolder"><span class="glyphicon glyphicon-plus"></span><span class="glyphicon glyphicon-tags"></span>&nbsp&nbspAdd Folders</a></li>
                              <li><a href="showallfolders"><span class="glyphicon glyphicon-tags"></span>&nbsp&nbspShow All Folders</a></li>
                              <hr/>
                              <li><a href="/showallcontacts"><span class="glyphicon glyphicon-user"></span>&nbsp&nbspShow Contacts</a></li>
                              <hr/>
                              <li><a href="/account"><span class="glyphicon glyphicon-plus"></span><span class="glyphicon glyphicon-briefcase"></span>&nbsp&nbspAdd Account</a></li>
                              <li><a href="/selectaccount"><span class="glyphicon glyphicon-briefcase">Show All Accounts</a></li>
                              <li><a href="/switchaccount"><span class="glyphicon glyphicon-off"></span>&nbsp&nbspSwitch Account</a></li>
                              <hr/>
                              <li><a href="/settings"><span class="glyphicon glyphicon-cog"></span>&nbsp&nbspSettings</a></li>
                              <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span>&nbsp&nbspLogout</a></li>
                            </ul>
                          </div><!--/.well -->
                        </div><!--/span-->
>>