settings() ::= <<

$mailboxTop()$
                    <div class="container-fluid">
                      <div class="row-fluid">
                        $mailboxLeft()$

                        <div class="span9">
                          <div class="hero-unit">
                          Settings: <br/>
                            <a href="/changepassword">Change Password</a>
                            </div>
                          </div>
                        </div><!--/span-->
                </div><!--/row-->
>>